### ISSUE TITLE
Can't resolve '../../dist' 

### ISSUE THREAD

**Issue by Sofiane-13** [jaumard/ngx-dashboard#41]
hello i get this error !
ERROR in ./src/app/my-widget/my-widget.component.ts
Module not found: Error: Can't resolve '../../dist' in '/home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/my-widget'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '../dist' in '/home/sofiane/Bureau/test/ngx-dashboard/demo/src/app'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '../dist' in '/home/sofiane/Bureau/test/ngx-dashboard/demo/src/app'
ERROR in /home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/my-widget/my-widget.component.ts (2,54): Cannot find module '../../dist'.
ERROR in /home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/app.component.ts (2,51): Cannot find module '../dist'.
ERROR in /home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/app.module.ts (5,33): Cannot find module '../dist'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ../dist relative to /home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/app.module.ts., resolving symbol AppModule in /home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/app.module.ts, resolving symbol AppModule in /home/sofiane/Bureau/test/ngx-dashboard/demo/src/app/app.module.ts
    at syntaxError (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@ngtools/webpack/src/plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/sofiane/Bureau/test/ngx-dashboard/demo/node_modules/@ngtools/webpack/src/plugin.js:493:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by jaumard** [comment]
Hello 

When doing what exactly ?

**Comment by Sofiane-13** [comment]
I want just run the project, and after i want to use it on my existing angular project.

**Comment by jaumard** [comment]
did you follow all the steps to make it run ? 

```
cd ngx-dashboard
npm i 
npm run build
cd demo 
npm i
cd src
ln -s ../../src/dist/ . 
cd ..
npm start
```
From the log it look like it miss the symlink

**Comment by Sofiane-13** [comment]
Yes and i have this error : 
```
ERROR in ./src/app/my-widget/my-widget.component.ts
Module not found: Error: Can't resolve '../../dist' in '/home/sofiane/Bureau/test2/ngx-dashboard/demo/src/app/my-widget'

```

**Comment by jaumard** [comment]
I just tried to checkout the project from scratch and follow the steps, and no problem on my side. Maybe you miss one step and did the symlink in the wrong place ?

**Comment by RahulRaj45** [comment]
Hi, I am getting the same errors. 

Please find the following error log.
Environment:
**OS:** Centos
**IDE:** Visual Studio Code
**Angular CLI:** 7.2.2
**Node:** 11.7.0

1)

ERROR in ./src/app/my-widget/my-widget.component.ts
Module not found: Error: Can't resolve '../../dist' in '/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/my-widget'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '../dist' in '/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '../dist' in '/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app'
ERROR in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/my-widget/my-widget.component.ts (2,54): Cannot find module '../../dist'.
ERROR in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.component.ts (2,51): Cannot find module '../dist'.
ERROR in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.module.ts (5,33): Cannot find module '../dist'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ../dist relative to /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.module.ts., resolving symbol AppModule in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.module.ts, resolving symbol AppModule in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.module.ts
    at syntaxError (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@ngtools/webpack/src/plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@ngtools/webpack/src/plugin.js:493:24)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

-------------------------------------------------------------

2) 
ERROR in ./src/app/my-widget/my-widget.component.ts
Module not found: Error: Can't resolve '../../dist' in '/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/my-widget'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '../dist' in '/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app'
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '../dist' in '/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app'
ERROR in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/my-widget/my-widget.component.ts (2,54): Cannot find module '../../dist'.
ERROR in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.component.ts (2,51): Cannot find module '../dist'.
ERROR in /home/krawler/Downloads/Angular/ngx-dashboard-master/demo/src/app/app.module.ts (5,33): Cannot find module '../dist'.
ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/typescript/lib/typescript.js:14876:110)
    at parseSourceFileWorker (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/typescript/lib/typescript.js:14808:26)
    at Object.parseSourceFile (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/typescript/lib/typescript.js:14757:26)
    at Object.createSourceFile (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/typescript/lib/typescript.js:14612:29)
    at new TypeScriptFileRefactor (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@ngtools/webpack/src/refactor.js:79:35)
    at Object.findLazyRoutes (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@ngtools/webpack/src/lazy_routes.js:18:22)
    at AotPlugin._findLazyRoutesInAst (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@ngtools/webpack/src/plugin.js:216:50)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/krawler/Downloads/Angular/ngx-dashboard-master/demo/node_modules/@ngtools/webpack/src/plugin.js:494:24)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

I have followed the same steps as mentioned 

cd ngx-dashboard
npm i 
npm run build
cd demo 
npm i
cd src ### **_( Where this command  redirects. I see there are two folders named as "src". 1. Under the demo/src  2. /src)_**
ln -s ../../src/dist/ . 
cd ..
npm start
